config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'home#index'

  resources :accounts, only: [:index, :update]
  
  resources :boxes, except: [:edit, :update, :destroy] do
    member do
      get 'qr_code', to: 'boxes#show_code'
    end
    
    resources :items, except: [:index, :destroy] do
      member do
        post 'use_item'
      end
    end
  end

  get 'add_users', to: 'users#new', as: 'add_new_user'
  post 'add_users', to: 'users#create', as: 'create_new_user'

  get 'billing_portal', to: 'billing_portal#new', as: 'billing_portal'
end

app/models/box.rb
class Box < ApplicationRecord
  acts_as_tenant(:account)
  has_many :items
  validates :name, presence: true, length: { maximum: 95 }
  validate :name_uniqueness_within_same_account
  validate :limit_boxes_according_to_plan

  def limit_boxes_according_to_plan
    if self.account.subscription
      limit = self.account.subscription.price.plan.box_limit
      if limit > 0 && self.new_record? && (self.account.boxes.count >= limit)
        errors.add(:base, "Your account cannot have more boxes than #{limit}")
      end
    else
      errors.add(:base, "Your account cannot create boxes")
    end
  end

  def name_uniqueness_within_same_account
    if self.new_record? && self.account.boxes.where('lower(name) = ?', name.downcase).first
      errors.add(:name, "has already been taken")
    end
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :account_have_been_choose?, only: [:show, :index, :new, :create]
  before_action :validate_user_belongs_to_account, only: [:show, :create, :show_code]
  before_action :set_box, only: [:show, :show_code]
  
  def index
    @boxes = current_account.boxes.all
  end

  def show
    unless @box
      not_found
    end
  end

  def show_code
    @qr_code = @box.qr_code
  end

  def new
    @box = Box.new
  end

  def create
    @box = Box.new(box_params.merge(account: current_account))
    if @box.save
      qr_code = generate_qr_code
      @box.update(qr_code: qr_code)
      flash[:notice] = "Box was created successfully."
      redirect_to @box
    else
      render 'new'
    end
  end

  private

  def set_box
    @box = current_account.boxes.where(id: params[:id]).first
  end

  def box_params
    params.require(:box).permit(:name)
  end

  def validate_user_belongs_to_account
    unless current_account.users.include?(current_user)
      flash[:alert] = "You don't have permissions to perform that action"
      redirect_to root_path
    end
  end

  def account_have_been_choose?
    unless current_account
      flash[:alert] = "You have to choose an account to perform that action"
      redirect_to accounts_path
    end
  end

  def generate_qr_code
    require 'rqrcode'
    box_dir = request.url + "/#{@box.id}"
    qr = RQRCode::QRCode.new(box_dir)
    qr_code = qr.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 11,
      standalone: true
    )
  end
end

app/views/boxes/index.html.erb
<h1>List Boxes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= box.name %></td>
        <td><%= link_to 'Show', box %></td>
        <td><%= link_to 'Add item', new_box_item_path(box) %></td>
        <td><%= link_to 'Show QRCode', qr_code_box_path(box) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New box</h1>
<%= render 'shared/errors', obj: @box %>
<%= form_with(model: @box) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boxes/show.html.erb
<h1>Show Box</h1>

<div>
  <strong>Name:</strong>
  <%= @box.name %>
</div>
<div>
  <%= link_to 'Add item', new_box_item_path(@box) %>
</div>
<div class="row">
  <% @box.items.each do |item| %>
    <div class="col-4">
      <% if item.picture.attached? %>
        <%= link_to image_tag(item.picture.variant(resize_to_limit: [300, 300])), box_item_path(box_id: @box, id: item.id) %>
      <% else %>
        <%= link_to "#{item.id}", box_item_path(box_id: @box, id: item.id) %>
      <% end %>
      <p><%= item.description %></p>
      <% if item.user %>
        <p>In use</p>
      <% end %>
    </div>
  <% end %>
</div>
<%= link_to 'Back', boxes_path %>

app/views/boxes/show_code.html.erb
<h1>Box's QRCode</h1>
<% if @qr_code %>
  <div>
    <%= @qr_code.html_safe %>
  </div>
<% else %>
  <p>Not available</p>
<% end %>