config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'home#index'

  resources :accounts, only: [:index, :update]
  
  resources :boxes, except: [:edit, :update, :destroy] do
    member do
      get 'qr_code', to: 'boxes#show_code'
    end
    
    resources :items, except: [:index, :destroy] do
      member do
        post 'use_item'
      end
    end
  end

  get 'add_users', to: 'users#new', as: 'add_new_user'
  post 'add_users', to: 'users#create', as: 'create_new_user'

  get 'billing_portal', to: 'billing_portal#new', as: 'billing_portal'
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mi Bodega</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if current_user && current_user_is_admin? %>
          <li class="nav-item">
            <%= link_to "Add Users", add_new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Billing", billing_portal_path, method: :get, class: "nav-link" %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Switch account', accounts_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Box
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "List boxes", boxes_path, class: "dropdown-item" %>
              <%= link_to "Create box", new_box_path, class: "dropdown-item" %>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Edit user", edit_user_registration_path, class: "dropdown-item" %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'Log Out', destroy_user_session_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>