config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'home#index'

  resources :accounts, only: [:index, :update]
  
  resources :boxes, except: [:edit, :update, :destroy] do
    member do
      get 'qr_code', to: 'boxes#show_code'
    end
    
    resources :items, except: [:index, :destroy] do
      member do
        post 'use_item'
      end
    end
  end

  get 'add_users', to: 'users#new', as: 'add_new_user'
  post 'add_users', to: 'users#create', as: 'create_new_user'

  get 'billing_portal', to: 'billing_portal#new', as: 'billing_portal'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :box
  belongs_to :user, optional: true
  has_one_attached :picture
  validates :description, presence: true
  validates :picture, presence: { message: "needs to be attached" }
  validate :image_type_validation

  def available_boxes
    boxes = []
    account = self.box.account
    account.boxes.each do |box|
      if box.id != self.box.id
        boxes.push([box.name.capitalize, box.id])
      end
    end
    boxes
  end

  private

  def image_type_validation
    valid_types = ["image/png", "image/jpeg"]
    if picture.attached? && !picture.content_type.in?(valid_types)
      errors.add(:picture, "must be a JPEG or PNG file.")
    end
  end

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :use_item, :edit, :update]

  def show
  end
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "Item was created successfully."
      redirect_to box_item_path(box_id: @item.box.id, id: @item.id)
    else
      render 'new'
    end
  end

  def use_item
    if @item.user == nil
      @item.user = current_user
      save_and_redirect
    elsif @item.user && @item.user == current_user
      @item.user = nil
      save_and_redirect
    else
      flash.now[:alert] = "Item is already in use"
      render 'show'
    end
  end

  def edit
  end

  def update
    new_box = Box.find(update_item_params[:new_box])
    if @item.box.account.boxes.include?(new_box)
      @item.box = new_box
      @item.save
      redirect_to new_box
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def save_and_redirect
    @item.save
    redirect_to box_item_path(box_id: @item.box.id, id: @item.id)
  end

  def item_params
    params.require(:item).permit(:description, :picture, :box_id)
  end

  def update_item_params
    params.require(:item).permit(:new_box)
  end
end

app/views/items/edit.html.erb
<h1>Move item</h1>

<%= render 'shared/errors', obj: @item %>
<% available_boxes = @item.available_boxes %>
<% if available_boxes.length > 0 %>
  <%= form_with(model: @item, url: box_item_path) do |f| %>
    <div>
      <%= f.label :new_box, 'New Box' %>
      <br>
      <%= f.select :new_box, options_for_select(@item.available_boxes, params[:new_box]), {}, required: true %>
    </div>

    <div class="actions">
      <%= f.submit "Move item" %>
    </div>
  <% end %>
<% else %>
  <p>Not enough boxes to move the item</p>
<% end %>

app/views/items/new.html.erb
<h1>Create a new item</h1>

<%= render 'shared/errors', obj: @item %>
<%= form_with(model: @item, url: box_items_path) do |f| %>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, placeholder: "Description of item" %>
  </div>
  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture, accept: "image/png, image/jpeg" %>
  </div>
  <%= f.hidden_field :box_id, value: params[:box_id] %>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/items/show.html.erb
<h1>Show item</h1>
<div>
  <strong>Description:</strong>
  <%= @item.description %>
</div>

<% if @item.picture.attached? %>
  <div>
    <%= image_tag @item.picture.variant(resize_to_limit: [300, 300]) %>
  </div>
<% end %>

<% if @item.user %>
  <% if @item.user == current_user %>
    <div>
      <%= form_with(url: use_item_box_item_path(box_id: @item.box.id, id: @item.id), local:true) do |w| %>
        <%= hidden_field_tag 'in_use', "false" %>
        <p>You are currently using this item, if you are done using it press button</p>
        <%= w.submit 'Done using item' %>
      <% end %>
    </div>

  <% else %>
    <p>Item is currently in use by a user</p>
  <% end %>

<% else %>
  <%= form_with(url: use_item_box_item_path(box_id: @item.box.id, id: @item.id), local:true) do |z| %>
    <p>Would you like to use the item?</p>
    <%= hidden_field_tag 'in_use', "true" %>
    <%= z.submit 'Use item' %>
  <% end %>
  <br>
  <div>
    <p>Would you like to move the item to another box?</p>
    <%= link_to 'Move item', edit_box_item_path %>
  </div>
<% end %>

<%= link_to 'Back', boxes_path %>